apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-static
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_GITHUB_USER/YOUR_REPO.git
    targetRevision: main
    path: charts/hello-static
    helm:
      releaseName: hello
  destination:
    server: https://kubernetes.default.svc
    namespace: hello
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
