apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 81.3.0
    helm:
      releaseName: mon
      values: |
        # Keep it lighter for Codespaces
        alertmanager:
          enabled: false

        grafana:
          enabled: true
          adminUser: admin
          adminPassword: admin
          service:
            type: ClusterIP
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi

        prometheus:
          prometheusSpec:
            retention: 6h
            resources:
              requests:
                cpu: 200m
                memory: 1Gi
              limits:
                memory: 2Gi

        # K3s/k3d commonly doesn't expose these like managed kubeadm clusters
        kubeEtcd:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
